### ISSUE TITLE
[Block] - Video

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/maestro#17]
Implement Video block as seen on https://maestro.maark.com/features

- [ ] Mobile version
- [ ] Desktop version
- [ ] See if this block can be auto-blocked

![Screenshot 2023-07-10 at 3 45 15 PM](https://github.com/hlxsites/maestro/assets/10811320/3ae412bc-9f88-40d1-ab09-59f6120e0afb)
![Screenshot 2023-07-10 at 3 45 54 PM](https://github.com/hlxsites/maestro/assets/10811320/69042b2b-172b-492f-bd9f-0d8641ee47e3)

**Comment by kunwarsaluja** [comment]
@jamesjtalbot @samuelopra  Please work together to see if we can combine video block and embed block in a single one so we dont do any repetitive work

**Comment by samuelopra** [comment]
@kunwarsaluja  - is this text not a sub-heading for the hero text? I don't think it should be in the same section as the video. Wdyt?

**Comment by kunwarsaluja** [comment]
@samuelopra I see this as default content that authors can edit whenever and is not part of the video block. 

This text could be a new section with all the styling and background-gray

**Comment by kunwarsaluja** [comment]
Moved to Media block and now closed per #51
